# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-09-02 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='article_body',
            field=models.TextField(max_length=2000),
        ),
    ]
