# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-09-22 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20160921_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='comments',
            field=models.PositiveIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
