# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-09-22 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_remove_comment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='timestamp',
        ),
    ]
