# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-10-02 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20161002_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
