# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-14 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hike',
            old_name='hike_logo',
            new_name='hike_map',
        ),
    ]
