# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-14 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0002_auto_20160714_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='hike_image',
            field=models.FileField(default=b'', upload_to=b''),
        ),
    ]
