# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-17 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0004_auto_20160717_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='hike_description',
            field=models.CharField(default='1000', max_length=1000),
            preserve_default=False,
        ),
    ]
