# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-09-21 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0006_auto_20160906_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hike',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hike',
            name='hike_image',
            field=models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=b'', width_field=b'width_field'),
        ),
    ]
