# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-10-02 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0007_auto_20160921_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='hike_image',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b''),
            preserve_default=False,
        ),
    ]
