# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-10-02 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0008_auto_20161002_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hike',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='hike',
            name='width_field',
        ),
    ]
